const mongoose=require("mongoose")
const conn=require("./mongo.db")
const newNewsSchema=new mongoose.Schema({
    title:[
        {
            en:{
                type:String,
                required:true,
            }
        },
        {
            hi:{
                type:String,
                required:true,
            }
        },
        {
            bn:{
                type:String,
                required:true,
            }
        },
        {
            gu:{
                type:String,
                required:true,
            }
        },
        {
            mr:{
                type:String,
                required:true,
            }
        },
        {
            kn:{
                type:String,
                required:true,
            }
        },
        {
            ml:{
                type:String,
                required:true,
            }
        },
        {
            ta:{
                type:String,
                required:true,
            }
        },
        {
            te:{
                type:String,
                required:true,
            }
        },
        {
            or:{
                type:String,
                required:true,
            }
        },
        {
            bn:{
                type:String,
                required:true,
            }
        },
        {
            as:{
                type:String,
                required:true,
            }
        },
    ],
    originalDescription:{
        type:String,
        required:true
    },
    description:[
        {
            en:{
                type:String,
                required:true,
            }
        },
        {
            hi:{
                type:String,
                required:true,
            }
        },
        {
            bn:{
                type:String,
                required:true,
            }
        },
        {
            gu:{
                type:String,
                required:true,
            }
        },
        {
            mr:{
                type:String,
                required:true,
            }
        },
        {
            kn:{
                type:String,
                required:true,
            }
        },
        {
            ml:{
                type:String,
                required:true,
            }
        },
        {
            ta:{
                type:String,
                required:true,
            }
        },
        {
            te:{
                type:String,
                required:true,
            }
        },
        {
            or:{
                type:String,
                required:true,
            }
        },
        {
            bn:{
                type:String,
                required:true,
            }
        },
        {
            as:{
                type:String,
                required:true,
            }
        },
    ],
    imageUrl:{
        type:String,
        required:String,
    }
})

const newNewsModel=conn.model("newnewses",newNewsSchema);
module.exports=newNewsModel;